# for database
spring.datasource.url=jdbc:mysql://localhost:3306/userdata
spring.datasource.username=root
spring.datasource.password=sandip
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
org.springframework.boot.autoconfigure.logging = INFO:
spring.thymeleaf.mode=LEGACYHTML5


spring.security.user.name=user
spring.security.user.password=123